### ISSUE TITLE
SQL problems

### ISSUE THREAD

**Issue by Jallot** [xSke/Pxls#33]
Exception in thread "main" org.skife.jdbi.v2.exceptions.UnableToObtainConnection
Exception: java.sql.SQLException: No suitable driver found for
        at org.skife.jdbi.v2.DBI.open(DBI.java:229)
        at org.skife.jdbi.v2.sqlobject.SqlObjectBuilder.open(SqlObjectBuilder.ja
va:50)
        at org.skife.jdbi.v2.DBI.open(DBI.java:401)
        at space.pxls.data.Database.<init>(Database.java:22)
        at space.pxls.App.main(App.java:52)
Caused by: java.sql.SQLException: No suitable driver found for
        at java.sql.DriverManager.getConnection(Unknown Source)
        at java.sql.DriverManager.getConnection(Unknown Source)
        at org.skife.jdbi.v2.DBI$3.openConnection(DBI.java:139)
        at org.skife.jdbi.v2.DBI.open(DBI.java:211)
        ... 4 more

I use Windows 7 32 bit

**Comment by Jallot** [comment]
How can i fix this error?

**Comment by Ukicu** [comment]
You either didn't copy the default config to the used config or you didn't fill it out correctly. I had the same issue. Copy the resources/reference.conf to pxls.conf and fill out the database section.
